# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.cache/wt} [current_project]
set_property parent.project_path {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/bram_test.coe}}
add_files {{D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/bram.coe}}
add_files {{d:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/bram.coe}}
read_verilog -library xil_defaultlib -sv {
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/data_extractor_mat_A.sv}
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/data_extractor_mat_B.sv}
}
read_verilog -library xil_defaultlib {
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/block.v}
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/data_feeder.v}
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/systolic_array.v}
  {D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/new/top_module.v}
}
read_ip -quiet {{D:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/MOODLE/SEMESTER 7/EN4020_Advanced_Digital_Systems/SoC_Project/Combined_setup/Fixed_8x8/Fixed_4X4_project/Fixed_4X4/Fixed_4X4.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
